#!/usr/bin/env python3
"""Emit docs/data.js for the interactive dashboard from the CSVs in data/.

Single source of truth: the same CSVs that feed the static charts. Computes
incidence per 100,000 (Census population, interpolated) and case fatality rate.
"""
import csv
import json
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")
DOCS = os.path.join(HERE, "..", "docs")
os.makedirs(DOCS, exist_ok=True)


def read_csv(name):
    with open(os.path.join(DATA, name)) as f:
        return list(csv.DictReader(f))


def to_int(v):
    v = (v or "").strip()
    return int(v) if v else None


def load_pop():
    rows = read_csv("us_population.csv")
    return (np.array([int(r["year"]) for r in rows]),
            np.array([int(r["population"]) for r in rows]))


def build(rows, case_field):
    pyrs, pop = load_pop()
    out = []
    for r in rows:
        y = int(r["year"])
        cases = to_int(r.get(case_field))
        deaths = to_int(r.get("deaths"))
        p = float(np.interp(y, pyrs, pop))
        inc = round(cases / p * 100000, 4) if cases is not None else None
        cfr = round(deaths / cases * 100, 4) if (cases and deaths is not None and cases > 0) else None
        out.append({"year": y, "cases": cases, "deaths": deaths,
                    "incidence": inc, "cfr": cfr, "note": r.get("notes", "")})
    return out


def early():
    rows = read_csv("early_mortality_rates.csv")
    return [{"year": int(r["year"]),
             "measles": float(r["measles_death_rate"]),
             "pertussis": float(r["pertussis_death_rate"])} for r in rows]


def main():
    data = {
        "vaccines": {
            "polio": [{"year": 1955, "label": "Salk IPV"},
                      {"year": 1961, "label": "Sabin OPV"}],
            "pertussis": [{"year": 1948, "label": "Whole-cell DTP"},
                          {"year": 1997, "label": "DTaP switch"}],
            "measles": [{"year": 1963, "label": "Measles vaccine"},
                        {"year": 1971, "label": "MMR"},
                        {"year": 1989, "label": "2nd dose"}],
        },
        "polio": build(read_csv("polio.csv"), "total_cases"),
        "pertussis": build(read_csv("pertussis.csv"), "reported_cases"),
        "measles": build(read_csv("measles.csv"), "reported_cases"),
        "earlyMortality": early(),
    }
    path = os.path.join(DOCS, "data.js")
    with open(path, "w") as f:
        f.write("// Auto-generated by scripts/build_dashboard_data.py — do not edit.\n")
        f.write("window.DISEASE_DATA = ")
        json.dump(data, f, indent=2)
        f.write(";\n")
    print("wrote", os.path.relpath(path, os.path.join(HERE, "..")))


if __name__ == "__main__":
    main()
